# **MTN Cote d'Ivoire -  Data Preparation and Data Analysis**

**1.0 Importing the Libraries to be used**

In [ ]:
# Since we will be utilization the numpy and pandas libraries in this notebook in the
# prearation and analysis os MTN Cote D'Ivore case, we begin by importing the two libraries
# into our programming environment.
import numpy as np # will import numpy library
import pandas as pd # to import pandas library

**1.1 Loading our Datasets**

Our data will be drawn from the below data files:

1. cells_geo_description.xlsx [Link]
2. cells_geo.csv [Link]
3. CDR_description.xlsx [Link]
4. CDR 20120507 [http://bit.ly/TelecomDataset1]
5. CDR 20120508 [http://bit.ly/TelecomDataset2]
6. CDR 20120509 [http://bit.ly/TelecomDataset3]

In [ ]:
# Having imported the libraries that we will use, the next step is to load our datasets to give us
# a clear picture of the type of date we will be dealing with and guide our next processes of its
# cleaning and later analysis.
# Lets now load our first data file containing the data geo decsrition.
url = 'https://docs.google.com/spreadsheets/d/1-rIM5ihDu79RaH7rAs-d-7SQSAQhrY9N/export?format=csv&gid=1058575376'

cell_geo_description = pd.read_csv(url)

# Lastly, view the rows
cell_geo_description

     Column name                                        Description  Format
0         VILLES                                               City  String
1         STATUS                                  In Service or not  String
2   LOCALISATION                                  in ABIDJAN or not  String
3     DECOUPZONE                                  Geographical Zone  String
4       ZONENAME                                       Name of Zone  String
5      LONGITUDE                                          Longitude   Float
6       LATITUDE                                           Latitude   Float
7         REGION                                             Region  String
8           AREA                                               Area  String
9        CELL_ID                                     ID of the cell  String
10     SITE_CODE  Site (there are several cells per site, severa...  String

The second file containing the cells geo data had errors and as such was unable to load it and use it in this project. Have experimented with three different options and each was produicing unusable output.

In [87]:
# Trying to load the dataset as a csv after uploading it to our environment but
# still the output is not usable since the data is not formatted into columns.
cells_geo = pd.read_csv(open('cells_geo.csv','r'))
cells_geo

     ;VILLES;STATUS;LOCALISATION;DECOUPZONE;ZONENAME;LONGITUDE;LATITUDE;REGION;AREA;CELL_ID;SITE_CODE
0     0;ADJAME;In Service;ABIDJAN;"""Abidjan_EST";AG...
1     1;ADJAME;In Service;ABIDJAN;"""Abidjan_EST";AG...
2     2;ADJAME;In Service;ABIDJAN;"""Abidjan_EST";AG...
3     3;ASSINIE;In Service;INTERIEUR;Grand-EST;"ASSI...
4     4;ASSINIE;In Service;INTERIEUR;Grand-EST;"ASSI...
...                                                 ...
3969  3969;ZUENOULA;In Service;INTERIEUR;Grand-NORD;...
3970  3970;ZUENOULA;In Service;INTERIEUR;Grand-NORD;...
3971  3971;ZUENOULA;In Service;INTERIEUR;Grand-NORD;...
3972  3972;ZUENOULA;In Service;INTERIEUR;Grand-NORD;...
3973  3973;ZUENOULA;In Service;INTERIEUR;Grand-NORD;...

[3974 rows x 1 columns]

In [90]:
# Installing excell writer to load the dataset as an excel file instead of using csv.
pip install openpyxl

Requirement already satisfied: openpyxl in /usr/local/lib/python3.7/dist-packages (2.5.9)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.7/dist-packages (from openpyxl) (1.1.0)
Requirement already satisfied: jdcal in /usr/local/lib/python3.7/dist-packages (from openpyxl) (1.4.1)

In [97]:
# Loading the file as an xlsx is not producing any usable output either
from openpyxl import load_workbook
cells_geo1 = load_workbook('cells_geo.xlsx')
print(cells_geo1)

<openpyxl.workbook.workbook.Workbook object at 0x7fdc3d0eded0>

In [33]:
# Load our second data file containing the cell geo data.
df_url = 'https://docs.google.com/spreadsheets/d/1cJCwy9GD0vTmiFkcRpIZebbWHeHUoqp7gD5HO5xUzkw/export?format=csv&gid=499625369'

col_names = ["VILLES", "STATUS", "LOCALISATION", "DECOUPZONE", "ZONENAME", "LONGITUDE", "LATITUDE", "REGION", "AREA", "CELL_ID", "SITE_CODE"]
cell_geo_data = pd.read_csv(df_url, names=col_names)

# Lastly, view the rows
cell_geo_data

# formatting the columns
cell_geo_data[['VILLES', 'STATUS', 'LOCALISATION', 'DECOUPZONE', 'ZONENAME', 'REGION', 'AREA', 'CELL_ID', 'SITE_CODE']] = cell_geo_data[['VILLES', 'STATUS', 'LOCALISATION', 'DECOUPZONE', 'ZONENAME', 'REGION', 'AREA', 'CELL_ID', 'SITE_CODE']].astype(str)

cell_geo_data[["LONGITUDE", "LATITUDE"]] = cell_geo_data[["LONGITUDE", "LATITUDE"]].apply(pd.to_numeric, errors='coerce')

cell_geo_data

                                                 VILLES  ... SITE_CODE
0                                       <!DOCTYPE html>  ...       nan
1                                      <html lang="en">  ...       nan
2                                                <head>  ...       nan
3                                <meta charset="utf-8">  ...       nan
4                              <meta content="width=300  ...       nan
...                                                 ...  ...       ...
1864    'https:\x2F\x2Faccounts.google.com\x2FServic...  ...       nan
1865    'https:\x2F\x2Faccounts.google.com\x2FPassiv...  ...       nan
1866                                          </script>  ...       nan
1867                                            </body>  ...       nan
1868                                            </html>  ...       nan

[1869 rows x 11 columns]

In [ ]:
# Next we load our third data file containing the CDR data description.
url = 'https://docs.google.com/spreadsheets/d/1cVoNXl25IO5-_yQk97ThdeqhE6yw8YTD/export?format=csv&gid=460839219'

CDR_description = pd.read_csv(url)

# Lastly, view the first ten rows
CDR_description.head(10)

       Column name                                        Description   Format
0          PRODUCT                                       Voice or SMS   String
1            VALUE                                      Billing price  Integer
2        DATE_TIME               Time in format yyyy-MM-dd hh:mm:ss.0   String
3     CELL_ON_SITE  Which cell in the site was used (not needed here)  Integer
4  DW_A_NUMBER_INT  Anonymized phone number of the person for whic...   String
5  DW_B_NUMBER_INT        Anonymized phone number of the counterparty   String
6        COUNTRY_A                  Country of party A (useless here)   String
7        COUNTRY_B                  Country of party B (useless here)   String
8          CELL_ID                                     ID of the cell   String
9          SITE_ID                                     ID of the SITE   String

In [34]:
# let us now load our fourth data file containing the CDR for the first day data.
url = 'http://bit.ly/Telcom_dataset1'

CDR_20120507= pd.read_csv(url)

# Lastly, view the first ten rows
CDR_20120507.head(10)

  PRODUTC  VALUE               DATETIME  ... COUNTRY_B     CELL_ID     SITE_ID
0   Voice      0  2012-05-06 23:04:37.0  ...     19e2e  /TJNe+Mmtu  /TJNe+Mmtu
1     sms      0  2012-05-06 23:05:25.0  ...     19e2e  /+cKZKIp41  /+cKZKIp41
2     sms     25  2012-05-06 23:05:41.0  ...     19e2e  /u0FSD+ahi  /u0FSD+ahi
3   Voice     56  2012-05-06 23:05:42.0  ...     19e2e  +cNeJzsTp3  +cNeJzsTp3
4   Voice     14  2012-05-06 23:06:29.0  ...     19e2e  051KhYDCpv  051KhYDCpv
5    data      0  2012-05-06 23:07:26.0  ...     OTHER  /lrUXVGVcN  /lrUXVGVcN
6   Voice      0  2012-05-06 23:08:02.0  ...     19e2e  +38u2u/rfx  +38u2u/rfx
7   Voice      0  2012-05-06 23:08:03.0  ...     19e2e  09UjmmY1Ds  09UjmmY1Ds
8   Voice      0  2012-05-06 23:08:05.0  ...     19e2e  0DeimCpZOc  0DeimCpZOc
9     sms      0  2012-05-06 23:08:43.0  ...     19e2e  01MDiY5F89  01MDiY5F89

[10 rows x 10 columns]

In [40]:
# let us now load our fifth data file containing the the second day CDR data.
url = 'http://bit.ly/Telcom_dataset2'

CDR_20120508= pd.read_csv(url)

# Lastly, view the first ten rows
CDR_20120508.head(10)#

  PRODUCT  VALUE              DATE_TIME  ... COUNTRY_B     CELL_ID     SITE_ID
0     sms      0  2012-05-07 23:02:06.0  ...     19e2e  +854AcBQT2  +854AcBQT2
1   Voice      0  2012-05-07 23:03:44.0  ...     19e2e  +854AcBQT2  +854AcBQT2
2     sms      0  2012-05-07 23:04:06.0  ...     19e2e  +laSrk7g6q  +laSrk7g6q
3   Voice     37  2012-05-07 23:04:48.0  ...     19e2e  /xvRrCVKoQ  /xvRrCVKoQ
4     sms     25  2012-05-07 23:04:58.0  ...     19e2e  +bO+qkSonO  +bO+qkSonO
5     sms      0  2012-05-07 23:05:41.0  ...     19e2e  /MMplBlWjh  /MMplBlWjh
6   Voice     41  2012-05-07 23:06:14.0  ...     19e2e  +laSrk7g6q  +laSrk7g6q
7   Voice     11  2012-05-07 23:06:28.0  ...     19e2e  +gySf02tKW  +gySf02tKW
8     sms      0  2012-05-07 23:06:35.0  ...     OTHER  /0FxP3az1x  /0FxP3az1x
9     sms      0  2012-05-07 23:06:50.0  ...     19e2e  0ecjmwPX21  0ecjmwPX21

[10 rows x 10 columns]

In [42]:
# Finally we will now load our sixth data file containing the CDR data for the third day.
url = 'http://bit.ly/Telcom_dataset3'

CDR_20120509= pd.read_csv(url)

# Lastly, view the first ten rows
CDR_20120509.head(10)

  PRODUCT  VALUE              DATE_TIME  ... COUNTRY_B      CELLID     SIET_ID
0   Voice     61  2012-05-08 23:01:28.0  ...     19e2e  +38u2u/rfx  +38u2u/rfx
1     sms      0  2012-05-08 23:01:31.0  ...     19e2e  +Fs4mTvdKx  +Fs4mTvdKx
2   Voice     10  2012-05-08 23:02:59.0  ...     19e2e  +ZaaZozy/+  +ZaaZozy/+
3     sms      0  2012-05-08 23:03:04.0  ...     19e2e  +cNeJzsTp3  +cNeJzsTp3
4   Voice     22  2012-05-08 23:03:16.0  ...     19e2e  /eeMklgyJA  /eeMklgyJA
5   Voice     10  2012-05-08 23:03:59.0  ...     19e2e  +e+xcimwre  +e+xcimwre
6     sms      0  2012-05-08 23:06:06.0  ...     19e2e  +R5ccmtyJf  +R5ccmtyJf
7   Voice     10  2012-05-08 23:06:55.0  ...     19e2e  +ZaaZozy/+  +ZaaZozy/+
8     sms     25  2012-05-08 23:07:09.0  ...     19e2e  13O1+JEun3  13O1+JEun3
9     sms      0  2012-05-08 23:07:38.0  ...     19e2e  /eeMklgyJA  /eeMklgyJA

[10 rows x 10 columns]

# **1.2 Data Analysis**

In [38]:
# Since now we have all our tables in order, we will then start to analyze the data.
# First we wll determine the average usage value for voice, data and sms for the 3 days.
# Day 1
average_value_1 = CDR_20120507['VALUE'].groupby(CDR_20120507['PRODUTC'])

# Displaying the mean value of the each product offered by MTN.
average_value_1.mean()

PRODUTC
Voice    49.062190
data      8.713755
sms       6.821772
Name: VALUE, dtype: float64

In [41]:
# Day 2
average_value_2 = CDR_20120508['VALUE'].groupby(CDR_20120508['PRODUCT'])

# Displaying the mean value of the each product offered by MTN.
average_value_2.mean()

PRODUCT
Voice    54.294858
data      7.180157
sms       5.458566
Name: VALUE, dtype: float64

In [43]:
# Day 3
average_value_3 = CDR_20120509['VALUE'].groupby(CDR_20120509['PRODUCT'])

# Displaying the mean value of the each product offered by MTN.
average_value_3.mean()

PRODUCT
Voice    65.047372
data      6.861472
sms       9.844958
Name: VALUE, dtype: float64

In [44]:
# Next we will dislay only those records where value of voice, was above
# the mean value for the various product
# Day 1
CDR_20120507[CDR_20120507['VALUE'] > 50]

     PRODUTC  VALUE               DATETIME  ... COUNTRY_B     CELL_ID     SITE_ID
3      Voice     56  2012-05-06 23:05:42.0  ...     19e2e  +cNeJzsTp3  +cNeJzsTp3
30     Voice    192  2012-05-06 23:12:43.0  ...     19e2e  1AX75JmPtt  1AX75JmPtt
32     Voice     99  2012-05-06 23:13:03.0  ...     19e2e  /u0FSD+ahi  /u0FSD+ahi
41     Voice   1610  2012-05-06 23:14:03.0  ...     19e2e  47yB6si0R9  47yB6si0R9
49     Voice    152  2012-05-06 23:15:41.0  ...     19e2e  54Pb8dz/52  54Pb8dz/52
...      ...    ...                    ...  ...       ...         ...         ...
4967   Voice     88  2012-05-07 00:01:53.0  ...     19e2e  03ee801971  7f76d66503
4969   Voice     90  2012-05-07 00:01:53.0  ...     19e2e  5f056fdcc9  1e0e1030e2
4970   Voice     60  2012-05-07 00:01:53.0  ...     19e2e  fd754bd0d0  e82c07d996
4973   Voice     90  2012-05-07 00:01:53.0  ...     19e2e  8930ae7091  4849c3cf05
4996     sms    100  2012-05-07 00:01:54.0  ...     OTHER  0c2371d9bc  1e751d08a4

[610 rows x 10 columns]

In [45]:
# Day 2
CDR_20120508[CDR_20120508['VALUE'] > 55]

     PRODUCT  VALUE              DATE_TIME  ... COUNTRY_B     CELL_ID     SITE_ID
35     Voice     90  2012-05-07 23:12:52.0  ...     19e2e  /0LopuZdd7  /0LopuZdd7
44     Voice    138  2012-05-07 23:13:29.0  ...     19e2e  3jZNkFBl6Y  3jZNkFBl6Y
72     Voice    194  2012-05-07 23:16:46.0  ...     19e2e  13O1+JEun3  13O1+JEun3
87     Voice     58  2012-05-07 23:18:57.0  ...     19e2e  /MMplBlWjh  /MMplBlWjh
95     Voice     62  2012-05-07 23:19:42.0  ...     19e2e  2q0YsSCxbH  2q0YsSCxbH
...      ...    ...                    ...  ...       ...         ...         ...
4971   Voice    101  2012-05-08 00:01:53.0  ...     19e2e  d970dcfc39  fb480113cd
4972   Voice     60  2012-05-08 00:01:53.0  ...     19e2e  b47a0101f9  8e6413d5b8
4974   Voice    400  2012-05-08 00:01:53.0  ...     19e2e  1d068e7a63  c550c9e238
4978   Voice    158  2012-05-08 00:01:53.0  ...     19e2e  ed472df66d  f3a6b6efd1
4982   Voice    405  2012-05-08 00:01:53.0  ...     19e2e  7ce0e70ac0  35cae15a08

[491 rows x 10 columns]

In [46]:
# Day 2
CDR_20120509[CDR_20120509['VALUE'] > 65]

     PRODUCT  VALUE              DATE_TIME  ... COUNTRY_B      CELLID     SIET_ID
32     Voice     67  2012-05-08 23:12:43.0  ...     19e2e  0BRdojv2my  0BRdojv2my
44     Voice     88  2012-05-08 23:14:03.0  ...     19e2e  4bv77IHLBw  4bv77IHLBw
46     Voice    159  2012-05-08 23:14:26.0  ...     19e2e  3/2ZhYCSrj  3/2ZhYCSrj
62     Voice     92  2012-05-08 23:16:10.0  ...     19e2e  0/eYPFomxx  0/eYPFomxx
65     Voice     82  2012-05-08 23:16:45.0  ...     19e2e  5bFHC1hRn8  5bFHC1hRn8
...      ...    ...                    ...  ...       ...         ...         ...
4944   Voice     93  2012-05-09 00:01:42.0  ...     19e2e  16e65def09  f9b7a55579
4946   Voice    266  2012-05-09 00:01:42.0  ...     19e2e  05813ba0f9  75bef3291a
4987   Voice    102  2012-05-09 00:01:43.0  ...     19e2e  d5bdd4f4cb  cdf82e4fe3
4992   Voice    236  2012-05-09 00:01:43.0  ...     19e2e  26c3cc23da  d2de5847b1
4993   Voice    219  2012-05-09 00:01:43.0  ...     19e2e  34f124cb0d  73dd78713b

[322 rows x 10 columns]

In [50]:
# Next we will find waht was the greatest usage value per day.
# Greatest usage vallue for the first day
CDR_20120507['VALUE'].max() # Day 1

4440

In [51]:
# Greatest usage vallue for the second day
CDR_20120508['VALUE'].max() # Day 2

3380

In [52]:
# Greatest usage vallue for the third day
CDR_20120509['VALUE'].max() # Day 3

12900

In [58]:
# It will also be helpful to find out which Cell IDs were unique in the three days.
# Day 1
CDR_20120507.CELL_ID.unique()

array(['/TJNe+Mmtu', '/+cKZKIp41', '/u0FSD+ahi', ..., '4a71bcb73f',
       '85bbd0e6b0', 'babc0339bd'], dtype=object)

In [59]:
# Day 2
CDR_20120508.CELL_ID.unique()

array(['+854AcBQT2', '+laSrk7g6q', '/xvRrCVKoQ', ..., '4e1d87caac',
       '896459aace', 'fe70e431df'], dtype=object)

In [60]:
# Day 3
CDR_20120509.CELLID.unique()

array(['+38u2u/rfx', '+Fs4mTvdKx', '+ZaaZozy/+', ..., '63cb899693',
       '425d28ede5', '6467daa1db'], dtype=object)

In [63]:
# To furher analyze the data, lets now find the Variance.
# Day 1
CDR_20120507['VALUE'].var()

10390.642599239554

In [64]:
# Day 2
CDR_20120508['VALUE'].var()

9500.709997441034

In [65]:
# Day 3
CDR_20120509['VALUE'].var()

50265.73742843004

In [67]:
# Lets now find the number of observations in each product and datetime
# Day 1
CDR_20120507.groupby(['PRODUTC', 'DATETIME']).size()

PRODUTC  DATETIME
Voice    2012-05-06 23:04:37.0     1
         2012-05-06 23:05:42.0     1
         2012-05-06 23:06:29.0     1
         2012-05-06 23:08:02.0     1
         2012-05-06 23:08:03.0     1
                                  ..
sms      2012-05-07 00:01:50.0    13
         2012-05-07 00:01:51.0    16
         2012-05-07 00:01:52.0    16
         2012-05-07 00:01:53.0    14
         2012-05-07 00:01:54.0     9
Length: 976, dtype: int64

In [68]:
# Day 2
CDR_20120508.groupby(['PRODUCT', 'DATE_TIME']).size()

PRODUCT  DATE_TIME
Voice    2012-05-07 23:03:44.0     1
         2012-05-07 23:04:48.0     1
         2012-05-07 23:06:14.0     1
         2012-05-07 23:06:28.0     1
         2012-05-07 23:08:16.0     1
                                  ..
sms      2012-05-08 00:01:49.0    24
         2012-05-08 00:01:50.0    18
         2012-05-08 00:01:51.0    20
         2012-05-08 00:01:52.0    18
         2012-05-08 00:01:53.0    20
Length: 1072, dtype: int64

In [69]:
# Day 3
CDR_20120509.groupby(['PRODUCT', 'DATE_TIME']).size()

PRODUCT  DATE_TIME
Voice    2012-05-08 23:01:28.0     1
         2012-05-08 23:02:59.0     1
         2012-05-08 23:03:16.0     1
         2012-05-08 23:03:59.0     1
         2012-05-08 23:06:55.0     1
                                  ..
sms      2012-05-09 00:01:39.0    24
         2012-05-09 00:01:40.0    23
         2012-05-09 00:01:41.0    17
         2012-05-09 00:01:42.0    16
         2012-05-09 00:01:43.0    22
Length: 885, dtype: int64

In [72]:
# We can do a random subset smpling of our date and pick a subset of three to see the likely otcome
# Day 1
CDR_20120507.take(np.random.permutation(len(CDR_20120507))[:3])

     PRODUTC  VALUE               DATETIME  ... COUNTRY_B     CELL_ID     SITE_ID
2930     sms      0  2012-05-07 00:00:58.0  ...     19e2e  3f7e9b72b5  d4b46cdec7
2277   Voice      0  2012-05-07 00:00:39.0  ...     19e2e  570868e59f  f850b9aa56
3274    data      0  2012-05-07 00:01:07.0  ...     OTHER  ffa6759bb2         NaN

[3 rows x 10 columns]

In [73]:
# Day 2
CDR_20120508.take(np.random.permutation(len(CDR_20120508))[:3])

     PRODUCT  VALUE              DATE_TIME  ... COUNTRY_B     CELL_ID     SITE_ID
4287     sms      0  2012-05-08 00:01:33.0  ...     19e2e  c916b4fdd1  dac8dcaeb9
1584     sms      0  2012-05-08 00:00:18.0  ...     19e2e  13c07f93cc  91ef65a206
4884    data      0  2012-05-08 00:01:51.0  ...     OTHER  ffa6759bb2         NaN

[3 rows x 10 columns]

In [74]:
# Day 3
CDR_20120509.take(np.random.permutation(len(CDR_20120509))[:3])

     PRODUCT  VALUE              DATE_TIME  ... COUNTRY_B      CELLID     SIET_ID
4343   Voice    242  2012-05-09 00:01:25.0  ...     OTHER  f4aceab2e2  739e843470
4135     sms     25  2012-05-09 00:01:20.0  ...     19e2e  96987d95ff  733b1c7315
3511     sms     50  2012-05-09 00:01:05.0  ...     19e2e  f54e480df9  928a59b635

[3 rows x 10 columns]

In [84]:
# Finally we will create a pivot table of the Products grouped by Date tme and by sum of their value
# Day 1
pd.pivot_table(CDR_20120507, index=['PRODUTC','DATETIME'], values=["VALUE"], aggfunc=np.sum)

                               VALUE
PRODUTC DATETIME
Voice   2012-05-06 23:04:37.0      0
        2012-05-06 23:05:42.0     56
        2012-05-06 23:06:29.0     14
        2012-05-06 23:08:02.0      0
        2012-05-06 23:08:03.0      0
...                              ...
sms     2012-05-07 00:01:50.0    125
        2012-05-07 00:01:51.0     75
        2012-05-07 00:01:52.0    175
        2012-05-07 00:01:53.0    100
        2012-05-07 00:01:54.0    200

[976 rows x 1 columns]

In [85]:
# Day 2
pd.pivot_table(CDR_20120508, index=['PRODUCT','DATE_TIME'], values=["VALUE"], aggfunc=np.sum)

                               VALUE
PRODUCT DATE_TIME
Voice   2012-05-07 23:03:44.0      0
        2012-05-07 23:04:48.0     37
        2012-05-07 23:06:14.0     41
        2012-05-07 23:06:28.0     11
        2012-05-07 23:08:16.0      0
...                              ...
sms     2012-05-08 00:01:49.0    100
        2012-05-08 00:01:50.0    100
        2012-05-08 00:01:51.0    175
        2012-05-08 00:01:52.0     25
        2012-05-08 00:01:53.0    225

[1072 rows x 1 columns]

In [105]:
# Day 3
pd.pivot_table(CDR_20120509, index=['PRODUCT','DATE_TIME'], values=["VALUE"], aggfunc=np.sum)

                               VALUE
PRODUCT DATE_TIME
Voice   2012-05-08 23:01:28.0     61
        2012-05-08 23:02:59.0     10
        2012-05-08 23:03:16.0     22
        2012-05-08 23:03:59.0     10
        2012-05-08 23:06:55.0     10
...                              ...
sms     2012-05-09 00:01:39.0    200
        2012-05-09 00:01:40.0    125
        2012-05-09 00:01:41.0    170
        2012-05-09 00:01:42.0    125
        2012-05-09 00:01:43.0    125

[885 rows x 1 columns]